Documentation in interview Page ( Issue #97)
tier3guy/Acadmica pull request #143
Opened 2022-08-26 17:21 UTC by Aman-Singh-Kushwaha

I have changed the content of the page :
- Replaced Lorem Ipsum Text with a good paragraph
- Improved grammatical errors in other paragraphs
- Made code more readable and aligned

### Before
![183274575-847c4f08-0a4c-49f0-8006-7c651ada1561](https://user-images.githubusercontent.com/96011814/186958079-2d8515be-8927-4911-9274-ce6b90f248fd.png)

### After
![image](https://user-images.githubusercontent.com/96011814/186958501-c58d0b6d-b528-45de-bc34-f017db903363.png)

2022-08-26 17:29 UTC, Aman-Singh-Kushwaha commented
Please note Lines Changed is showing this much because I haven't synced previous upstream changes before committing changes in my master repo. At the last push, I synced and solved conflicts by accepting others' latest code and my contributed lines.
I assure that the code is correct

2022-08-26 17:36 UTC, Aman-Singh-Kushwaha commented
I have contributed to Line no: 
100 - 111
230 - 237
347

2022-08-28 18:19 UTC, narayan954 requested changes
I have highlighted some minor typos or issues in the updated documentation. Please have a look.
PS: Please take these as constructive feedbacks

2022-08-28 18:19 UTC, narayan954 commented on src/pages/interviewPrep/main.html
> +        While choosing a language as a beginner, you must have a purpose at least roughly known in your mind and the
Can you please work more on grammar in lines 101,103,etc . For example, in line 101 it'd be better to have "time you <b>are ready</b>(or want) to give." . 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-28 18:19 UTC, narayan954 commented on src/pages/interviewPrep/main.html
> +        If you want to learn programming from scratch and have enough time, C++ will be the best also for DSA and
In line 103 "C++ could be the best option for both DSA and" 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-28 18:19 UTC, narayan954 commented on src/pages/interviewPrep/main.html
> +        which had been always a harder step.
in line 109 , it could be improved as " which had always been the harder step."

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-28 18:19 UTC, narayan954 commented on src/pages/interviewPrep/main.html
> +        Learning DSA will give you an idea of how this real-life application works and the most important thing - top
in line 232, perhaps it could be "these real-life applications work"

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-28 18:19 UTC, narayan954 commented on src/pages/interviewPrep/main.html
> +        Expected time period: There is no limit to learning DSA, people working in the tech industry also sometimes
in line 235 it could be "even people working in the tech industry sometimes"

2022-08-28 18:19 UTC, narayan954 commented on src/pages/interviewPrep/main.html
> +        "Computer fundamentals" gives us an insight into the underlying base - working of the computer, computer
Line 349 could be better as " Computer fundamentals give us an ......" (Removed " and gives to give)

2022-08-30 07:57 UTC, merged